"""Validated B97-3c harmonic-IR reference consumers.

The implementation remains NumPy-only so reference artifacts can be audited
without importing Psi4, Torch, ALCHEMI Toolkit, or plotting libraries.
"""

from .core import (
    HESSIAN_EIGENVALUE_TO_CM1,
    IR_ARTIFACT_SCHEMA,
    IR_ARTIFACT_VERSION,
    HarmonicIRReference,
    HydrogenBondedOH,
    IRArtifactError,
    IRSpectrumComparison,
    IsotopologueModeMatch,
    ModeSubspaceMatch,
    NormalModeSolution,
    SpectralBandSummary,
    WaterRingModeCharacters,
    compare_md_to_harmonic_reference,
    discrete_hann_power_response,
    hann_resolution_envelope,
    independently_max_normalize,
    label_water_monomer_modes,
    load_psi4_b973c_ir_artifact,
    match_isotopologue_modes,
    raw_ir_sticks,
    reference_water_monomer_mode_labels,
    reference_water_ring_mode_characters,
    solve_vibrational_modes,
    summarize_spectral_band,
    water_ring_mode_characters,
)

__all__ = [
    "HESSIAN_EIGENVALUE_TO_CM1",
    "IR_ARTIFACT_SCHEMA",
    "IR_ARTIFACT_VERSION",
    "HarmonicIRReference",
    "HydrogenBondedOH",
    "IRArtifactError",
    "IRSpectrumComparison",
    "IsotopologueModeMatch",
    "ModeSubspaceMatch",
    "NormalModeSolution",
    "SpectralBandSummary",
    "WaterRingModeCharacters",
    "compare_md_to_harmonic_reference",
    "discrete_hann_power_response",
    "hann_resolution_envelope",
    "independently_max_normalize",
    "label_water_monomer_modes",
    "load_psi4_b973c_ir_artifact",
    "match_isotopologue_modes",
    "raw_ir_sticks",
    "reference_water_monomer_mode_labels",
    "reference_water_ring_mode_characters",
    "solve_vibrational_modes",
    "summarize_spectral_band",
    "water_ring_mode_characters",
]
