"""Shared numerical settings for model composition and compilation checks.

The notebook displays these methodology values and applies them explicitly.
The external run validator imports the same names, which prevents a saved run
from being accepted under limits that differ from the learner-facing checks.
"""

from __future__ import annotations


COMPOSITION_FD_STEP_A = 3.0e-3
COMPOSITION_FD_FORCE_TOLERANCE_EV_A = 2.0e-3
COMPOSITION_FD_ENERGY_ROUTE = "official AIMNet2Calculator total energy"
COMPOSITION_ENERGY_AGREEMENT_TOLERANCE_EV = 1.0e-3
COMPOSITION_INTERACTION_AGREEMENT_TOLERANCE_EV = 1.0e-3
COMPOSITION_FORCE_AGREEMENT_TOLERANCE_EV_A = 3.0e-6
COMPOSITION_CHARGE_AGREEMENT_TOLERANCE_E = 2.0e-7
COMPOSITION_ANALYTIC_COULOMB_ENERGY_TOLERANCE_EV = 2.0e-6
COMPOSITION_ANALYTIC_COULOMB_FORCE_TOLERANCE_EV_A = 2.0e-6

# Agreement limits for equivalent Toolkit execution routes.  These are strict
# numerical checks on the same model and inputs, not model-accuracy targets.
RESIDUAL_SERIAL_BATCH_TOLERANCE_EV = 1.0e-5
FULL_SERIAL_BATCH_TOLERANCE_EV = 2.0e-5
COMPONENT_CLOSURE_TOLERANCE_EV = 2.0e-5
COMPILED_EAGER_ENERGY_TOLERANCE_EV = 5.0e-6
COMPILED_EAGER_FORCE_TOLERANCE_EV_A = 5.0e-6
COMPILED_EAGER_CHARGE_TOLERANCE_E = 2.0e-7
COMPILED_REPEAT_ENERGY_TOLERANCE_EV = 2.0e-6
COMPILED_REPEAT_FORCE_TOLERANCE_EV_A = 2.0e-6
COMPILED_REPEAT_CHARGE_TOLERANCE_E = 1.0e-7


__all__ = [
    "COMPOSITION_ANALYTIC_COULOMB_ENERGY_TOLERANCE_EV",
    "COMPOSITION_ANALYTIC_COULOMB_FORCE_TOLERANCE_EV_A",
    "COMPOSITION_CHARGE_AGREEMENT_TOLERANCE_E",
    "COMPOSITION_ENERGY_AGREEMENT_TOLERANCE_EV",
    "COMPOSITION_FD_ENERGY_ROUTE",
    "COMPOSITION_FD_FORCE_TOLERANCE_EV_A",
    "COMPOSITION_FD_STEP_A",
    "COMPOSITION_FORCE_AGREEMENT_TOLERANCE_EV_A",
    "COMPOSITION_INTERACTION_AGREEMENT_TOLERANCE_EV",
    "COMPONENT_CLOSURE_TOLERANCE_EV",
    "COMPILED_EAGER_CHARGE_TOLERANCE_E",
    "COMPILED_EAGER_ENERGY_TOLERANCE_EV",
    "COMPILED_EAGER_FORCE_TOLERANCE_EV_A",
    "COMPILED_REPEAT_CHARGE_TOLERANCE_E",
    "COMPILED_REPEAT_ENERGY_TOLERANCE_EV",
    "COMPILED_REPEAT_FORCE_TOLERANCE_EV_A",
    "FULL_SERIAL_BATCH_TOLERANCE_EV",
    "RESIDUAL_SERIAL_BATCH_TOLERANCE_EV",
]
