"""Shared numerical method settings for the Part 1 harmonic comparison."""

from __future__ import annotations

import numpy as np


HARMONIC_FIRE_INITIAL_DT = 0.01
HARMONIC_FIRE_MAX_STEPS = 10_000
HARMONIC_FMAX_EV_A = 5.0e-4
HARMONIC_DISPLACEMENT_STEPS_BOHR = np.array([0.020, 0.010, 0.005])
HARMONIC_DISPLACEMENT_STEPS_BOHR.setflags(write=False)
HARMONIC_SELECTED_STEP_BOHR = 0.005
HARMONIC_FREQUENCY_STEP_TOLERANCE_CM1 = 2.0
HARMONIC_INTENSITY_STEP_ABS_TOLERANCE_KM_MOL = 1.0
HARMONIC_INTENSITY_STEP_REL_TOLERANCE = 0.05
HARMONIC_MODE_OVERLAP_MIN = 0.99
HARMONIC_HESSIAN_ANTISYMMETRY_REL_MAX = 1.0e-3
HARMONIC_CHARGE_NEUTRALITY_TOLERANCE_E = 5.0e-5
HARMONIC_IMAGINARY_FLOOR_CM1 = -10.0


__all__ = [
    "HARMONIC_CHARGE_NEUTRALITY_TOLERANCE_E",
    "HARMONIC_DISPLACEMENT_STEPS_BOHR",
    "HARMONIC_FIRE_INITIAL_DT",
    "HARMONIC_FIRE_MAX_STEPS",
    "HARMONIC_FMAX_EV_A",
    "HARMONIC_FREQUENCY_STEP_TOLERANCE_CM1",
    "HARMONIC_HESSIAN_ANTISYMMETRY_REL_MAX",
    "HARMONIC_IMAGINARY_FLOOR_CM1",
    "HARMONIC_INTENSITY_STEP_ABS_TOLERANCE_KM_MOL",
    "HARMONIC_INTENSITY_STEP_REL_TOLERANCE",
    "HARMONIC_MODE_OVERLAP_MIN",
    "HARMONIC_SELECTED_STEP_BOHR",
]
