name: alchemi-b973c-ir
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ase=3.29
  - psi4=1.11
  - dftd3-python>=1.3
  - gcp-correction>=2.3
  - geometric>=1.1
  - matplotlib>=3.9
  - numpy>=2.0
  - pytest>=8
