"""Programmatic starter-molecule geometries for the SEI Pareto challenge.

The challenge does NOT depend on any structure files: every structure is built in
code. Surfaces come from pymatgen (``Structure.from_spacegroup`` / inline COD CIF +
``SlabGenerator``); the starter molecules below are embedded idealized geometries
constructed as ``ase.Atoms``.

Provenance: each geometry was generated once from its SMILES with RDKit ETKDGv3
conformer embedding + MMFF94 optimisation (12 conformers, seed 2026, lowest-energy
conformer kept, centred on the centroid). They are idealized teaching geometries —
the notebook's MLIP relaxation refines them before any energy is used, exactly as it
did for the previous file-based geometries.

Adding literature molecules: call :func:`register_molecule` (e.g. from a
``custom_molecules.py`` next to the notebook) with an ``ase.Atoms`` built from
coordinates you trust — constructed inline, via ``ase.build.molecule`` for G2
species, or from a pymatgen ``Molecule``. No xyz files are needed.
"""

from __future__ import annotations

from collections import Counter

# candidate_id -> (comment ignored) (symbols, coords) generated by RDKit as described above.
_STARTER_GEOMETRIES: dict[str, tuple[tuple[str, ...], tuple[tuple[float, float, float], ...]]] = {
    # EC: SMILES C1COC(=O)O1, formula C3H4O3
    "EC": (
        ("C", "C", "O", "C", "O", "O", "H", "H", "H", "H"),
        ((-0.5243, 0.8167, -0.0862), (-0.7105, -0.6404, 0.1854), (0.5207, -1.1983, -0.2333),
         (1.4553, -0.2078, -0.1169), (2.6580, -0.3795, -0.2135), (0.8632, 1.0007, 0.1221),
         (-0.7606, 1.0833, -1.1219), (-1.1094, 1.4473, 0.5886), (-1.5459, -1.0682, -0.3753),
         (-0.8466, -0.8539, 1.2510)),
    ),
    # EMC: SMILES CCOC(=O)OC, formula C4H8O3
    "EMC": (
        ("C", "C", "O", "C", "O", "O", "C", "H", "H", "H", "H", "H", "H", "H", "H"),
        ((-2.7247, 0.7068, -0.0212), (-1.5578, -0.2577, 0.0649), (-0.3463, 0.4940, -0.0498),
         (0.7798, -0.2593, 0.0127), (0.8235, -1.4722, 0.1530), (1.8490, 0.5666, -0.1074),
         (3.1051, -0.1062, -0.0573), (-2.6662, 1.4549, 0.7762), (-2.7054, 1.2515, -0.9710),
         (-3.6770, 0.1755, 0.0620), (-1.6207, -0.9867, -0.7509), (-1.5808, -0.7795, 1.0284),
         (3.2330, -0.6108, 0.9057), (3.1929, -0.8191, -0.8832), (3.8955, 0.6423, -0.1621)),
    ),
    # FEC: SMILES FC1COC(=O)O1, formula C3H3FO3
    "FEC": (
        ("F", "C", "C", "O", "C", "O", "O", "H", "H", "H"),
        ((-0.4711, 1.2775, 1.3259), (-0.4159, 0.8609, 0.0365), (-0.7955, -0.5798, -0.0610),
         (0.4283, -1.2441, 0.2040), (1.4262, -0.3516, -0.0740), (2.6104, -0.6397, -0.1056),
         (0.9318, 0.8866, -0.3574), (-1.0377, 1.5198, -0.5750), (-1.5517, -0.8694, 0.6731),
         (-1.1247, -0.8602, -1.0665)),
    ),
    # VC: SMILES C1=COC(=O)O1, formula C3H2O3
    "VC": (
        ("C", "C", "O", "C", "O", "O", "H", "H"),
        ((-0.7473, 0.6570, -0.1796), (-0.7935, -0.6117, 0.1359), (0.4525, -1.1476, 0.2958),
         (1.2490, -0.0367, 0.0354), (2.4728, -0.0726, 0.0702), (0.5350, 1.1186, -0.2678),
         (-1.5365, 1.3603, -0.3717), (-1.6321, -1.2673, 0.2818)),
    ),
    # TMP: SMILES COP(=O)(OC)OC, formula C3H9O4P
    "TMP": (
        ("C", "O", "P", "O", "O", "C", "O", "C", "H", "H", "H", "H", "H", "H", "H", "H", "H"),
        ((-0.1655, 2.5176, -0.4262), (-0.7120, 1.2284, -0.6106), (0.0180, 0.0228, 0.1683),
         (0.1756, 0.2228, 1.6427), (-0.8440, -1.2688, -0.2579), (-2.1310, -1.3814, 0.3126),
         (1.3940, -0.1650, -0.6467), (2.2646, -1.1767, -0.1849), (-0.2474, 2.8141, 0.6229),
         (0.8826, 2.5351, -0.7369), (-0.7270, 3.2277, -1.0384), (-2.7365, -0.5061, 0.0623),
         (-2.0535, -1.4818, 1.3985), (-2.6168, -2.2735, -0.0903), (1.7609, -2.1470, -0.1959),
         (3.1326, -1.2222, -0.8474), (2.6054, -0.9459, 0.8279)),
    ),
    # succinonitrile: SMILES N#CCCC#N, formula C4H4N2
    "succinonitrile": (
        ("N", "C", "C", "C", "C", "N", "H", "H", "H", "H"),
        ((-1.9807, 1.7102, -0.7780), (-1.3916, 0.7334, -0.5704), (-0.6574, -0.5050, -0.2812),
         (0.5112, -0.2541, 0.6636), (1.6162, 0.4328, -0.0170), (2.4941, 0.9556, -0.5649),
         (-1.3458, -1.2172, 0.1891), (-0.3127, -0.9637, -1.2156), (0.8768, -1.2179, 1.0376),
         (0.1899, 0.3260, 1.5368)),
    ),
}

# Runtime registry: starter molecules plus anything added via register_molecule().
_REGISTRY: dict[str, object] = {}


def register_molecule(candidate_id: str, atoms) -> None:
    """Register an ``ase.Atoms`` geometry (or zero-arg builder) for ``candidate_id``.

    Use this for literature molecules instead of shipping structure files: build the
    ``Atoms`` in code (inline coordinates, ``ase.build.molecule``, or a pymatgen
    ``Molecule`` converted via its ``to_ase_atoms()``/``ase`` adapter) and register it
    before calling :func:`build_molecule`. Re-registering an id overwrites it.
    """
    _REGISTRY[str(candidate_id)] = atoms


def known_molecules() -> tuple[str, ...]:
    """All candidate_ids that build_molecule() can currently construct."""
    return tuple(sorted(set(_STARTER_GEOMETRIES) | set(_REGISTRY)))


def build_molecule(candidate_id: str):
    """Construct the molecule for ``candidate_id`` as a fresh ``ase.Atoms``.

    Starter-panel molecules come from the embedded idealized geometries above;
    custom molecules must first be added with :func:`register_molecule`.
    """
    from ase import Atoms

    if candidate_id in _REGISTRY:
        entry = _REGISTRY[candidate_id]
        atoms = entry() if callable(entry) else entry.copy()
        return atoms
    if candidate_id in _STARTER_GEOMETRIES:
        symbols, coords = _STARTER_GEOMETRIES[candidate_id]
        return Atoms(symbols=list(symbols), positions=[list(c) for c in coords])
    raise KeyError(
        f"Unknown molecule {candidate_id!r}. Known ids: {', '.join(known_molecules())}. "
        "For literature molecules, register an ase.Atoms geometry with "
        "challenge_utils.molecules.register_molecule(candidate_id, atoms) "
        "(e.g. from a custom_molecules.py next to the notebook)."
    )


def molecule_formula(candidate_id: str) -> str:
    """Hill-style formula (C, H, then alphabetical) for cross-checking the manifest."""
    if candidate_id in _REGISTRY:
        entry = _REGISTRY[candidate_id]
        atoms = entry() if callable(entry) else entry
        symbols = atoms.get_chemical_symbols()
    else:
        symbols = _STARTER_GEOMETRIES[candidate_id][0]
    counts = Counter(symbols)
    order = ["C", "H"] + sorted(k for k in counts if k not in ("C", "H"))
    return "".join(f"{el}{counts[el] if counts[el] > 1 else ''}" for el in order if el in counts)
