"""Support code for the GPU pipelines and profiling deep dive."""

from .lesson import (
    COMPLETED_UPDATE_COLUMN,
    MODEL_ALIAS,
    AtomicDataset,
    MoleculeDataset,
    PipelineMonitor,
    configure_presentation,
    device_memory_snapshot,
    filter_known_native_stderr,
    freeze_model,
    load_molecule_selection,
    make_synthetic_graphs,
    model_checkpoint,
    per_system_fmax,
    plot_measurement_panels,
    plot_pipeline_diagnostics,
    probe_gpu_buffer_mixed_dtype,
    profile_artifacts,
    render_figure,
    repo_root,
    runtime_identity,
    stage_timing_frame,
    start_tutorial,
    summarize_collected,
    synchronize,
    time_callable,
)

__all__ = [
    "COMPLETED_UPDATE_COLUMN",
    "MODEL_ALIAS",
    "AtomicDataset",
    "MoleculeDataset",
    "PipelineMonitor",
    "configure_presentation",
    "device_memory_snapshot",
    "filter_known_native_stderr",
    "freeze_model",
    "load_molecule_selection",
    "make_synthetic_graphs",
    "model_checkpoint",
    "per_system_fmax",
    "plot_measurement_panels",
    "plot_pipeline_diagnostics",
    "probe_gpu_buffer_mixed_dtype",
    "profile_artifacts",
    "render_figure",
    "repo_root",
    "runtime_identity",
    "stage_timing_frame",
    "start_tutorial",
    "summarize_collected",
    "synchronize",
    "time_callable",
]
