#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Reproduce the tutorial's declared Python/conda environment and generate a
# committed third-party package license inventory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

CONDA_BIN="${CONDA_BIN:-conda}"
UV_BIN="${UV_BIN:-uv}"
PYTHON_VERSION="${PYTHON_VERSION:-3.12}"
ENV_DIR="${ENV_DIR:-$REPO_ROOT/.venv-licenses}"
OUT_DIR="$REPO_ROOT/.licenses"
REQUIREMENTS="$REPO_ROOT/build/requirements.txt"
ENVIRONMENT="$REPO_ROOT/build/environment.yml"
CONDA_LOCK="$REPO_ROOT/build/conda-linux-64.lock"
PIP_LOCK="$REPO_ROOT/build/requirements-linux-64.lock.txt"
export UV_CACHE_DIR="${UV_CACHE_DIR:-$ENV_DIR/.uv-cache}"

if [[ "$ENV_DIR" != /* ]]; then
  ENV_DIR="$REPO_ROOT/$ENV_DIR"
fi
case "$ENV_DIR" in
  "$REPO_ROOT"/.venv-licenses*) ;;
  *)
    echo "Refusing unsafe ENV_DIR outside $REPO_ROOT/.venv-licenses*" >&2
    exit 2
    ;;
esac

PY="$ENV_DIR/bin/python"

if [[ "${REUSE_ENV:-0}" != "1" ]]; then
  echo ">>> creating fresh inventory environment at $ENV_DIR"
  rm -rf "$ENV_DIR"
  "$CONDA_BIN" env create \
    --prefix "$ENV_DIR" \
    --file "$ENVIRONMENT" \
    --yes

  echo ">>> installing the CUDA 13 Torch package"
  "$UV_BIN" pip install \
    --python "$PY" \
    "torch==2.13.0+cu130" \
    --index-url https://download.pytorch.org/whl/cu130

  echo ">>> installing the tutorial requirements"
  "$UV_BIN" pip install \
    --python "$PY" \
    --no-sources-package nvalchemi-toolkit-ops \
    --requirement "$REQUIREMENTS"
fi

if [[ ! -x "$PY" ]]; then
  echo "Inventory environment is missing $PY" >&2
  exit 2
fi

echo ">>> exporting exact Linux x86_64 build locks"
"$PY" - "$ENV_DIR" "$CONDA_LOCK" "$PIP_LOCK" "$CONDA_BIN" <<'PYEOF'
import json
import subprocess
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


env_dir = Path(sys.argv[1]).resolve()
conda_lock_path = Path(sys.argv[2])
pip_lock_path = Path(sys.argv[3])
conda_bin = sys.argv[4]

conda_explicit = subprocess.check_output(
    [conda_bin, "list", "--prefix", str(env_dir), "--explicit"],
    text=True,
)
conda_lock_path.write_text(
    "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
    "#\n"
    "# Exact conda package lock for the Linux x86_64 tutorial environment.\n"
    "# Generated by .licenses/generate_licenses.sh; do not edit by hand.\n"
    + conda_explicit,
    encoding="utf-8",
)

conda_packages = json.loads(
    subprocess.check_output(
        [conda_bin, "list", "--prefix", str(env_dir), "--json"],
        text=True,
    )
)
pypi_names = {
    canonicalize_name(package["name"])
    for package in conda_packages
    if package["channel"] == "pypi"
}
pypi_names.discard("pip-licenses")

freeze_lines = subprocess.check_output(
    [str(env_dir / "bin" / "python"), "-m", "pip", "freeze"],
    text=True,
).splitlines()
locked = {}
for line in freeze_lines:
    requirement = Requirement(line)
    name = canonicalize_name(requirement.name)
    if name in pypi_names:
        locked[name] = line

missing = sorted(pypi_names - set(locked))
if missing:
    raise SystemExit(
        "Installed PyPI packages missing from pip freeze: " + ", ".join(missing)
    )

header = [
    "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.",
    "# SPDX-License-Identifier: Apache-2.0",
    "#",
    "# Exact Python package lock for the Linux x86_64 tutorial environment.",
    "# Generated by .licenses/generate_licenses.sh; do not edit by hand.",
    "# Torch is installed first from https://download.pytorch.org/whl/cu130.",
    "",
]
pip_lock_path.write_text(
    "\n".join(header + [locked[name] for name in sorted(locked)]) + "\n",
    encoding="utf-8",
)
PYEOF

RAW_JSON="$(mktemp)"
trap 'rm -f "$RAW_JSON"' EXIT

echo ">>> collecting installed Python package licenses"
"$UV_BIN" pip install --python "$PY" pip-licenses==4.1
"$ENV_DIR/bin/pip-licenses" \
  --format=json \
  --with-license-file \
  --with-urls > "$RAW_JSON"

echo ">>> rendering direct-dependencies.md, summary.md, details.json, and Third_party_attr.txt"
OVERRIDES="$OUT_DIR/license-overrides.json" \
"$PY" - "$RAW_JSON" "$OUT_DIR" "$REPO_ROOT" "$ENV_DIR" <<'PYEOF'
import json
import os
import re
import sys
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


raw_path = Path(sys.argv[1])
out_dir = Path(sys.argv[2])
repo_root = Path(sys.argv[3])
env_dir = Path(sys.argv[4])


def declared_dependencies():
    declared = {}

    requirements = repo_root / "build" / "requirements.txt"
    for raw_line in requirements.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        req = Requirement(line)
        declared[canonicalize_name(req.name)] = {
            "name": req.name,
            "declaration": line,
            "declared_in": "build/requirements.txt",
        }

    environment = repo_root / "build" / "environment.yml"
    in_dependencies = False
    for raw_line in environment.read_text(encoding="utf-8").splitlines():
        if raw_line.rstrip() == "dependencies:":
            in_dependencies = True
            continue
        if not in_dependencies:
            continue
        match = re.match(r"^  - ([A-Za-z0-9_.-]+)(.*)$", raw_line)
        if not match:
            continue
        name = match.group(1)
        declaration = f"{name}{match.group(2).strip()}"
        declared.setdefault(
            canonicalize_name(name),
            {
                "name": name,
                "declaration": declaration,
                "declared_in": "build/environment.yml",
            },
        )

    dockerfile = repo_root / "build" / "Dockerfile"
    for raw_line in dockerfile.read_text(encoding="utf-8").splitlines():
        match = re.search(
            r"\buv pip install ([A-Za-z0-9][A-Za-z0-9_.-]*)\b",
            raw_line,
        )
        if not match:
            continue
        name = match.group(1)
        declared.setdefault(
            canonicalize_name(name),
            {
                "name": name,
                "declaration": name,
                "declared_in": "build/Dockerfile",
            },
        )

    return declared


def load_overrides():
    path = Path(os.environ["OVERRIDES"])
    if not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {
        canonicalize_name(name): value
        for name, value in payload.get("overrides", {}).items()
    }


def clean_license_file(value):
    if not value:
        return "UNKNOWN"
    text = str(value)
    try:
        relative = Path(text).resolve().relative_to(env_dir.resolve())
    except (OSError, ValueError):
        return text
    return f"<inventory-environment>/{relative.as_posix()}"


declared = declared_dependencies()
overrides = load_overrides()
data = [
    record
    for record in json.loads(raw_path.read_text(encoding="utf-8"))
    if canonicalize_name(record["Name"]) != "pip-licenses"
]

by_name = {}
for record in data:
    normalized = canonicalize_name(record["Name"])
    try:
        dist = distribution(record["Name"])
        metadata = dist.metadata
    except PackageNotFoundError:
        dist = None
        metadata = None
    if metadata is not None:
        license_expression = (metadata.get("License-Expression") or "").strip()
        metadata_license = (metadata.get("License") or "").strip()
        current_license = (record.get("License") or "UNKNOWN").strip()
        if license_expression:
            record["License"] = license_expression
        elif current_license.upper() == "UNKNOWN" and metadata_license:
            first_line = next(
                (line.strip() for line in metadata_license.splitlines() if line.strip()),
                "UNKNOWN",
            )
            record["License"] = (
                first_line if len(first_line) <= 100 else metadata_license
            )
        elif "\n" in current_license or len(current_license) > 80:
            first_line = next(
                (line.strip() for line in metadata_license.splitlines() if line.strip()),
                "",
            )
            if first_line and len(first_line) <= 100:
                record["License"] = first_line

        if (record.get("URL") or "UNKNOWN").strip().upper() == "UNKNOWN":
            project_urls = []
            for value in metadata.get_all("Project-URL") or []:
                label, separator, url = value.partition(",")
                if separator and url.strip():
                    project_urls.append((label.strip().lower(), url.strip()))
            for preferred_label in ("repository", "source", "homepage"):
                preferred = next(
                    (
                        url
                        for label, url in project_urls
                        if label == preferred_label
                    ),
                    "",
                )
                if preferred:
                    record["URL"] = preferred
                    break
            else:
                record["URL"] = (
                    (metadata.get("Home-page") or "").strip()
                    or (project_urls[0][1] if project_urls else "UNKNOWN")
                )

        if (record.get("LicenseText") or "UNKNOWN").strip().upper() == "UNKNOWN":
            license_paths = []
            for relative in dist.files or []:
                path = Path(str(relative))
                basename = path.name.upper()
                if (
                    "LICENSES" in {part.upper() for part in path.parts}
                    or basename.startswith(("LICENSE", "COPYING", "NOTICE"))
                ):
                    located = Path(dist.locate_file(relative))
                    if located.is_file():
                        license_paths.append(located)
            if license_paths:
                record["LicenseText"] = "\n\n".join(
                    f"===== {path.name} =====\n"
                    + path.read_text(encoding="utf-8", errors="replace").strip()
                    for path in sorted(set(license_paths))
                )
                record["LicenseFile"] = ", ".join(
                    clean_license_file(path) for path in sorted(set(license_paths))
                )
            elif "\n" in metadata_license:
                record["LicenseText"] = metadata_license
                record["LicenseFile"] = "Installed package metadata"

    record["LicenseFile"] = clean_license_file(record.get("LicenseFile"))
    record["Direct"] = normalized in declared
    record["DeclaredIn"] = (
        declared[normalized]["declared_in"] if normalized in declared else ""
    )
    record["Declaration"] = (
        declared[normalized]["declaration"] if normalized in declared else ""
    )
    if (
        normalized in declared
        and (record.get("URL") or "UNKNOWN").strip().upper() == "UNKNOWN"
    ):
        try:
            declared_url = Requirement(record["Declaration"]).url
        except ValueError:
            declared_url = None
        if declared_url:
            record["URL"] = declared_url
    by_name[normalized] = record

for meta_path in sorted((env_dir / "conda-meta").glob("*.json")):
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    normalized = canonicalize_name(meta["name"])
    license_id = (meta.get("license") or "UNKNOWN").strip()
    extracted_dir = Path(meta.get("extracted_package_dir") or "")
    license_root = extracted_dir / "info" / "licenses"
    license_paths = (
        sorted(path for path in license_root.rglob("*") if path.is_file())
        if license_root.is_dir()
        else []
    )
    license_text = "\n\n".join(
        f"===== {path.relative_to(license_root).as_posix()} =====\n"
        + path.read_text(encoding="utf-8", errors="replace").strip()
        for path in license_paths
    )
    license_file = (
        ", ".join(
            f"<conda-package>/info/licenses/"
            f"{path.relative_to(license_root).as_posix()}"
            for path in license_paths
        )
        if license_paths
        else "Conda package metadata"
    )
    if normalized in by_name:
        record = by_name[normalized]
        if (record.get("License") or "UNKNOWN").strip().upper() == "UNKNOWN":
            record["License"] = license_id
        if (
            (record.get("LicenseText") or "UNKNOWN").strip().upper() == "UNKNOWN"
            and license_text
        ):
            record["LicenseText"] = license_text
            record["LicenseFile"] = license_file
        if (record.get("URL") or "UNKNOWN").strip().upper() == "UNKNOWN":
            record["URL"] = meta.get("url") or meta.get("channel") or "UNKNOWN"
        continue
    record = {
        "Name": meta["name"],
        "Version": meta.get("version") or "UNKNOWN",
        "License": license_id,
        "LicenseFile": license_file,
        "LicenseText": (
            license_text
            or (
                f"Conda package metadata reports license: {license_id}. "
                "Review the package source URL for the complete applicable terms."
            )
        ),
        "URL": meta.get("url") or meta.get("channel") or "UNKNOWN",
        "Direct": normalized in declared,
        "DeclaredIn": (
            declared[normalized]["declared_in"] if normalized in declared else ""
        ),
        "Declaration": (
            declared[normalized]["declaration"] if normalized in declared else ""
        ),
    }
    data.append(record)
    by_name[normalized] = record

applied = []
for normalized, override in overrides.items():
    record = by_name.get(normalized)
    if record is None:
        continue
    record["License"] = override["license"]
    if override.get("license_text"):
        record["LicenseText"] = override["license_text"]
    elif override.get("license_text_file"):
        license_path = repo_root / override["license_text_file"]
        record["LicenseText"] = license_path.read_text(
            encoding="utf-8",
        ).strip()
        record["LicenseFile"] = override["license_text_file"]
    elif (record.get("LicenseText") or "UNKNOWN").strip().upper() == "UNKNOWN":
        record["LicenseText"] = override.get("evidence", override["license"])
    record["LicenseEvidence"] = override.get("evidence", "")
    applied.append(record["Name"])

missing_direct = sorted(set(declared) - set(by_name))
if missing_direct:
    names = ", ".join(declared[name]["name"] for name in missing_direct)
    raise SystemExit(f"Declared dependencies missing from inventory: {names}")

data.sort(
    key=lambda record: (
        not record["Direct"],
        (record.get("License") or "UNKNOWN").lower(),
        record["Name"].lower(),
    )
)

(out_dir / "details.json").write_text(
    json.dumps(data, indent=2, sort_keys=True) + "\n",
    encoding="utf-8",
)


def cell(value):
    text = str(value or "UNKNOWN").replace("|", r"\|")
    return " ".join(text.split())


def short_license(value):
    text = str(value or "").strip()
    if not text:
        return "UNKNOWN"
    if "\n" in text or len(text) > 80:
        return "<full text; see details.json>"
    return text


def markdown_table(records, include_scope):
    columns = ["Name", "Version", "License", "Declared in", "URL"]
    if include_scope:
        columns.insert(0, "Scope")
    rows = []
    for record in records:
        row = [
            cell(record["Name"]),
            cell(record["Version"]),
            cell(short_license(record.get("License"))),
            cell(record.get("DeclaredIn") or ""),
            cell(record.get("URL")),
        ]
        if include_scope:
            row.insert(0, "direct" if record["Direct"] else "transitive")
        rows.append(row)
    header = "| " + " | ".join(columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    body = "\n".join("| " + " | ".join(row) + " |" for row in rows)
    return f"{header}\n{divider}\n{body}\n"


direct_records = [record for record in data if record["Direct"]]
(out_dir / "direct-dependencies.md").write_text(
    "# Direct third-party dependencies\n\n"
    "Generated from the dependency declarations used to build the tutorial "
    "environment. License texts and additional metadata are available in "
    "[details.json](details.json) and "
    "[Third_party_attr.txt](Third_party_attr.txt).\n\n"
    + markdown_table(direct_records, include_scope=False),
    encoding="utf-8",
)

(out_dir / "summary.md").write_text(
    "# Installed package license summary\n\n"
    "This generated snapshot includes both direct and transitive packages in "
    "the reproduced tutorial environment.\n\n"
    + markdown_table(data, include_scope=True),
    encoding="utf-8",
)

blocks = []
for record in data:
    fields = [
        f"Name: {record['Name']}",
        f"Version: {record['Version']}",
        f"Scope: {'direct' if record['Direct'] else 'transitive'}",
        f"License: {record.get('License') or 'UNKNOWN'}",
        f"URL: {record.get('URL') or 'UNKNOWN'}",
        f"License file: {record.get('LicenseFile') or 'UNKNOWN'}",
    ]
    if record.get("DeclaredIn"):
        fields.append(f"Declared in: {record['DeclaredIn']}")
    if record.get("LicenseEvidence"):
        fields.append(f"License evidence: {record['LicenseEvidence']}")
    fields.extend(["", record.get("LicenseText") or "UNKNOWN"])
    blocks.append("\n".join(fields))

(out_dir / "Third_party_attr.txt").write_text(
    "\n\n" + ("\n\n" + ("-" * 79) + "\n\n").join(blocks) + "\n",
    encoding="utf-8",
)

unknown = [
    record
    for record in data
    if (record.get("License") or "UNKNOWN").strip().upper() == "UNKNOWN"
]
missing_text = [
    record
    for record in data
    if (record.get("LicenseText") or "UNKNOWN").strip().upper() == "UNKNOWN"
]
print(
    f">>> done: {len(data)} installed packages; "
    f"{len(direct_records)} direct; {len(applied)} overrides"
)
if unknown:
    print(">>> UNKNOWN license identifiers:")
    for record in unknown:
        print(f"      {record['Name']} {record['Version']}")
if missing_text:
    print(">>> missing license text:")
    for record in missing_text:
        print(f"      {record['Name']} {record['Version']}")
if unknown or missing_text:
    raise SystemExit("License inventory is incomplete")
PYEOF

echo ">>> inventory complete"
