"""Learner-facing support for the domain-decomposition deep dive."""

from .lesson import (
    CampaignReport,
    accessible_figure,
    array_sha256,
    base_box_identity,
    build_argon_control,
    campaign_spec_path,
    campaign_workload_frame,
    configure_presentation,
    control_summary,
    evidence_status_frame,
    installed_pin_table,
    plot_campaign,
    plot_control_parity,
    plot_domain_ownership,
    read_campaign_spec,
    reorder_by_source_id,
    repo_root,
    sha256_file,
    validate_campaign,
)

__all__ = [
    "CampaignReport",
    "accessible_figure",
    "array_sha256",
    "base_box_identity",
    "build_argon_control",
    "campaign_spec_path",
    "campaign_workload_frame",
    "configure_presentation",
    "control_summary",
    "evidence_status_frame",
    "installed_pin_table",
    "plot_campaign",
    "plot_control_parity",
    "plot_domain_ownership",
    "read_campaign_spec",
    "reorder_by_source_id",
    "repo_root",
    "sha256_file",
    "validate_campaign",
]
